title: We Used to be Fun...
description: A podcast about our family of four where we discuss parenting, life events, argue about stuff, and hear from our adorable children.
author: Levi and Amy
email: levi.j.elston@gmail.com
lang: en-us
copyright: "&#xA9; 2019"
logo: /assets/img/WeUsedToBeFun_logo.png
rss_feed: /podcast.rss
twitter_url: https://www.twitter.com/weusedtobefun
apple_url: https://podcasts.apple.com/us/podcast/we-used-to-be-fun/id1451681576
google_url: https://podcasts.google.com/feed/aHR0cHM6Ly93ZXVzZWR0b2JlZnVuLnBvZGJlYW4uY29tL2ZlZWQueG1s?sa=X&ved=2ahUKEwjI97iy39L2AhWjgokEHQ0zDV4Q9sEGegQIARAC
spotify_url: https://open.spotify.com/show/3dzxUTWxRNKVLWKiJVt6Bi
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
